services:
  - type: web
    name: login-backend
    runtime: python
    buildCommand: "pip install -r app/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHONPATH
        value: .
